version: "3"
services:
  mongo:
    container_name: mongo-database
    image: mongo
    restart: always
    volumes:
      - ~/mongo-data:/data/db
    ports:
      - 27017:27017

  api:
    container_name: api-clean-node-container
    build: .
    image: clean-node-api
    command: npm start
    volumes:
      - ./dist:/user/src/app/dist
    ports:
      - 5050:5050
      - 5000:5000
    links:
      - mongo
