version: "3"
services:
  mongo:
    container_name: mongo-database
    image: mongo
    restart: always
    volumes:
      - ~/mongo-data:/data/db
    ports:
      - 27017:27017

  api:
    container_name: api-clean-node-container
    image: node:17
    working_dir: /user/src/app
    command: bash -c "npm install --only=prod && npm run debug"
    volumes:
      - ./dist/:/user/src/app/dist/
      - ./package.json:/user/src/app/package.json
    ports:
      - 5050:5050
      - 9222:9222
    links:
      - mongo
